### ISSUE TITLE
CircleCI fails

### ISSUE THREAD

**Issue by minamorl** [sketchglass/respass#29]
node v6系統とそれ以前でnode_modulesに共通性がないらしくSequelizeがエラーを吐く．
報告されている問題は https://github.com/kriasoft/react-starter-kit/issues/587 に同じ．
CircleCIがランダムで以下のエラーを発する．

```
$npm test

> respass@1.0.0 pretest /home/ubuntu/respass
> npm run compile:ts


> respass@1.0.0 compile:ts /home/ubuntu/respass
> tsc


> respass@1.0.0 test /home/ubuntu/respass
> mocha lib/test

/home/ubuntu/respass/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25
      throw new Error('Please install sqlite3 package manually');
      ^
```

https://circleci.com/gh/sketchglass/respass/16

Rebuild without cache すると修正できるが，これを取り除きたい．

**Comment by minamorl** [comment]
22003a599a0bc6fd8ce0a7a90bacae91b3dde59d でとりあえず対応したけどしばらく様子見

**Comment by minamorl** [comment]
なんか解決してそう?

**Comment by seanchas116** [comment]
1回リビルドしたからなおったんですかね

**Comment by minamorl** [comment]
とりあえずクローズしておきます
