### ISSUE TITLE
全メッセージを取得できるAPIをつくる

### ISSUE THREAD

**Issue by seanchas116** [sketchglass/respass#6]
全メッセージを取得できるAPIをつくる
- express でエンドポイントをつくる?
- ~~websocketでもいい気がする~~

**Comment by minamorl** [comment]
express でエンドポイントを作るに vote します

**Comment by seanchas116** [comment]
別にwebsocketをわざわざ使わなくてもいいのでexpressでよさそう

**Comment by seanchas116** [comment]
これやってみます

**Comment by minamorl** [comment]
！！ 了解です

**Comment by seanchas116** [comment]
あ、やりたかったとかなら別に大丈夫です (どうしましょう)

**Comment by minamorl** [comment]
ちょっとバックエンド疲れたのでお任せしていいですか．笑
`/server/` 以下に`server.ts`とかで足す感じでいいと思います
よろしくお願いします

**Comment by seanchas116** [comment]
OKです!
